### PR TITLE
Update CalculateWallForces.m

### PR DESCRIPTION
**Pull request by HelstVadsom**
To do: buy me a beer. :P

### CODE REVIEW

**Comment by andjohae** [comment]
Why are the collision forces removed?

Although, if your new distance calculation works I **will** absolutely buy you a beer!

**Comment by HelstVadsom** [comment]
Uhm maybe I accedentally removed it... [&#X1f61d]

Or Maybe it wasn't needed, don't remember.

**Comment by andjohae** [comment]
Okay, I see that you just commented that section so I guess it's easily recovered! 

The collision forces surely are needed? Agents should still be able to collide with the wall? I'm talking about the _bodyForce_ and _frictionForce_.
**Note:** The fact that you removed these may cause smoother behaviour of the model, but it would be incorrect.

**Comment by HelstVadsom** [comment]
Hej Vart är vi någonstans?

**Comment by HelstVadsom** [comment]
Sitter du på skolan?

**Comment by andjohae** [comment]
Nej men har ätit nu och ska strax åka in. Nils är på skolan, du får höra av dig till honom! Kommer typ 14:30

**Pull request merged**
